pr:
  branches:
    include:
      - main

pool: #telling what operation system we will be using 
  name: self-hosted-windows 

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test'
    jdkVersionOption: '11'
